### ISSUE TITLE
P1 : Error: network buffer full

### ISSUE THREAD

**Issue by bruvv** [romix123/ESPEasyDSMR5#2]
Hallo Romix,

Thanks voor al je werk! Ik heb mijn nieuwe meter de Landis + Gyr E360 met SMR5.0 en mijn P1 wifi gateway werkt helaas niet meer... hiervoor had ik een 4.0 en die werkte prima. De error die ik zie in de log is:
```P1 : Error: network buffer full```
Nieuwste firmware (19 Mei)
Kan het zijn dat ik het nieuwe Parasitaire P1P-wifi Gateway design nodig heb ivm dat de slimme meter de D1 nu ook van stroom voorziet en daardoor read errors komen?

**Comment by asterixonline** [comment]
> Hallo Romix,
> 
> Thanks voor al je werk! Ik heb mijn nieuwe meter de Landis + Gyr E360 met SMR5.0 en mijn P1 wifi gateway werkt helaas niet meer... hiervoor had ik een 4.0 en die werkte prima. De error die ik zie in de log is:
> `P1 : Error: network buffer full`
> Nieuwste firmware (19 Mei)
> Kan het zijn dat ik het nieuwe Parasitaire P1P-wifi Gateway design nodig heb ivm dat de slimme meter de D1 nu ook van stroom voorziet en daardoor read errors komen?

Heb je hier nog een oplossing voor gevonden?

**Comment by romix123** [comment]
Ha Asterix!,

In beginsel is de hardware gelijk. Wat de parasitaire versie anders maakt is de buffer elco en bijbehorende aansluitingen op de RJ12.
In de firmware die je gebruikt staat de buffer op 2k. Berichten zijn ongeveer 1k, dus in beginsel zouden er geen bufffer overflows mogen zijn. Als de wemos echter de stopcode mist, gebeurt dat evident wel. Ik ie alleen niet direct waarom de wemos de stopcodes zou missen (bij andere ontvangstfouten dropt hij de boodschap en reset de buffer).
Is de jumper geinstalleerd? Dat zou wel moeten op een L+G.
Je kan web debug level eens op 5 kunnen zetten onder tools advanced. Je ziet dan de telegrammen in de log langs komen. Als berichten te lang zijn zal je dat daar zien.
Iets anders is dat je de  verwerkingsfrequentie naar beneden kan gooien (samples). Een 5 meter levert iedere sec een meting af, een 4 iedere 10 sec. De wemos zou 1 per sec makkelijk aan moeten kunnen, maar ik zie niet echt andere mogelijke oorzaken.
Ik krijg erg weinig meldingen van het probleem dat je schetst. Een of twee keer eerder gehoord. Er zijn nu denk ik zo’n 200 modules op esmr 5 in gebruik. Dit is niet bedoeld als dooddoener, maar ik kan het niet goed verklaren.


Ronald

Verstuurd vanaf mijn iPad

**Comment by bruvv** [comment]
Geen idee meer het werkt inmiddels
